### PR TITLE
Several orthogonal fixes

### LINKED ISSUE #87: Uncaught TypeError: Cannot assign to read only property 'prevTime'
Hi, noticed the Chrome extension is throwing this error for some pages. Example case is [reddit](http://reddit.com). Full error is:

```
Uncaught TypeError: Cannot assign to read only property 'prevTime' of <!doctype html><html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">[the whole page is displayed]</body></html>
```

According to the console, the error is specifically coming from `info.prevTime = Date.now().toString();`, in the following block:

```
if (info == null || shouldRenew) {
    var req = new XMLHttpRequest();
    try {  
      req.open('GET', "/tipsy.txt", false);   
    } catch (e) {

    }
    try {
      req.send(null);  
    } catch(e) {
      localStorage.setItem(document.domain, JSON.stringify({'tipsyTried': Date.now()}));
    }
    if (req.status == 200) {
      version = req.responseText.split("\n")[0];

      if (version == "0.0.1") { 

        info = Date.now().toString() + "\n" + req.responseText;
        localStorage.setItem(document.domain, info);
      } else {
        info = req.responseText;

        try {
          info = jsyaml.load(info);
        } catch (e) {}
        info.prevTime = Date.now().toString();
        localStorage.setItem(document.domain, JSON.stringify(info));
      }
    } else {
      localStorage.setItem(document.domain, JSON.stringify({'tipsyTried': Date.now()}));
    }
  } else {
    info = localStorage.getItem(document.domain);
  }
```

### PR DESCRIPTION
**Pull request by rht**
Fixes #87

### CODE REVIEW

**Comment by rht** [comment]
The travis ci has yet to run `npm run test-chrome` or `npm run test-firefox`.

**Comment by karger** [comment]
Hey, thanks for your PR.  We're still maintaining this code, but the person who knows travis hasn't been around.  I'll see if I can figure out why the integration checks are failing.

**Comment by rht** [comment]
Actually, I just fixed the travis code partially. I 1. upgraded the dist from precise to trusty, which uses the latest version of chrome, 2. bumped node and selenium versions as well.
ref thread: https://github.com/travis-ci/travis-ci/issues/5899

Now the travis runs the `npm run test` but with chrome test disabled due to an outdated setup code.

File: chrome-extension/test/configure.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
 'use strict';
+process.exit();
```
Comment (Stebalien) [inline chrome-extension/test/configure.js]: Any reason this is still here? Unless I'm mistaken, this disables the entire test.

File: .travis.yml [hunk 2]
```diff
@@ -1,30 +1,25 @@
...
+
+addons:
+  apt:
+    sources:
+    - google-chrome
+    packages:
+    - google-chrome-stable
+
+before_script:
   - "sudo chmod 1777 /dev/shm"
```
Comment (Stebalien) [inline .travis.yml]: I wonder if this is still needed (I'm not the original dev so I don't know what it fixed. Other than that, this change looks good.

File: shared/scripts/lib/utils/tipsy-txt-parser.js [hunk 3]
```diff
@@ -105,8 +105,9 @@ export function parseTxt() {
         try {
           info = jsyaml.load(info);
         } catch (e) {}
-        info.prevTime = Date.now().toString();
-        localStorage.setItem(document.domain, JSON.stringify(info));
+        var serialInfo = JSON.parse(JSON.stringify(info)); // copy object or non-object without jquery
```
Comment (Stebalien) [inline shared/scripts/lib/utils/tipsy-txt-parser.js]: LGTM (but I wish there were a better way to do this...).

File: shared/scripts/lib/processors/dwolla.js [hunk 4]
```diff
@@ -9,12 +9,6 @@ export function inject($el, amount, token) {
   var redirect = [root, base, 'Dwolla user', amount].join('/');
   var src = 'https://www.dwolla.com/scripts/button.min.js';
 
-  // If we're in testing, swap the token with our test account.
-  if (localStorage.testing === 'true') {
-    token = 'lYNGTjRZRQAU4j32+qB4fBAPNDTQQGeZHF9cZFrH+83qm21sTL';
-    src = base + '/../../vendor/dwolla.js';
-  }
-
```
Comment (Stebalien) [inline shared/scripts/lib/processors/dwolla.js]: I'm not the original dev but I'm pretty sure this is as intended and is not a security issue. These tokens appear to be public identifiers and this code exists to avoid spamming legitimate Dwolla accounts when testing.

Unfortunately, I can't find any sites that actually use Dwolla and I'm not even sure if this API is still working...

File: chrome-extension/test/configure.js [hunk 5]
```diff
@@ -9,21 +10,21 @@ ExtensionDriver.prototype.navigate = function(url) {
...
+  var options = new chrome.Options();
+  options.addExtensions(path.resolve('chrome-extension/dist/tipsy.crx'), function() {
+    test.driver = new chrome.Driver(options, service);
 
-  return this.extensionDriver.navigate('html/index.html');
+    //driver.manage().timeouts().implicitlyWait(1000);
+    test.extensionDriver = new ExtensionDriver(test.driver, id);
+    test.extensionDriver.navigate('html/index.html').then(done);
+  });
 });
```
Comment (Stebalien) [inline chrome-extension/test/configure.js]: David,

This looks reasonable (but I'm not familiar with this interface). If it passes, it should be good.

**Comment by karger** [comment]
that disablement is there because the test isn't working, so it was 
disabled to let the rest pass.

File: .travis.yml (hunk 2 above)
Comment (rht) [inline .travis.yml]: Noted: I have removed the `chmod` line and the travis test still passes. An additional reason for reference: https://docs.travis-ci.com/user/gui-and-headless-browsers/ doesn't require the `chmod` line either.

File: chrome-extension/test/configure.js (hunk 1 above)
Comment (rht) [inline chrome-extension/test/configure.js]: + https://github.com/haystack/tipsy/pull/91#issuecomment-275725578
+ Having a test running for firefox is better than having no test. Fixing the chromium part depends on refreshing the versions in the deps in package.json + rewriting the chromium test with an updated api

Comment (Stebalien) [inline chrome-extension/test/configure.js]: I asked because https://github.com/haystack/tipsy/pull/91/commits/4989d57b71641725e506f1095b183e7effb8307c (a later commit) appears to be trying to fix the chrome test. Does that fix not work?

File: .travis.yml (hunk 2 above)
Comment (Stebalien) [inline .travis.yml]: Thanks (and sorry for making you do extra work 😺).

File: chrome-extension/test/configure.js (hunk 1 above)
Comment (rht) [inline chrome-extension/test/configure.js]: It did not, but I could fix this in a PR later (if absolutely necessary). That commit was followed by another one to disable the chromium test. The scope of this PR is to fix #87, and enabling the test is and addition.

Comment (Stebalien) [inline chrome-extension/test/configure.js]: Ah. Got it. (I thought you might have forgotten to remove this).

Comment (Stebalien) [inline chrome-extension/test/configure.js]: Could you change the commit message in https://github.com/haystack/tipsy/pull/91/commits/4989d57b71641725e506f1095b183e7effb8307c to "Make chrome test less broken" (or something like that). It seems like a strict improvement but the commit message is a bit misleading.

**Comment by Stebalien** [comment]
Other than changing that commit message, LGTM.

**Comment by rht** [comment]
Commit message clarification addressed.
